// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by grpc_generate_tools(grpcgengo) at
package usercenter

import (
	"context"
	"github.com/google/martian/log"

	jsoniter "github.com/json-iterator/go"
	"github.com/pengcainiao2/zero/rpcx/grpcbase"
)

var (
	GetUserHandler func(ctx context.Context, req GetUserRequest) grpcbase.Response
)

type Repository interface {
	GetUser(ctx context.Context, request GetUserRequest) grpcbase.Response
}

type Any struct {
	type_url string `json:"type_url,omitempty"`
	value    []byte `json:"value,omitempty"`
}

func (s Any) String() string {
	b, _ := jsoniter.Marshal(s)
	return string(b)
}

type GetUserRequest struct {
	Keyword string       `json:"keyword,omitempty"`
	Context *UserContext `json:"context,omitempty"`
}

func (s GetUserRequest) String() string {
	b, _ := jsoniter.Marshal(s)
	return string(b)
}

type GetUserResponse struct {
	Name string `json:"name,omitempty"`
}

func (s GetUserResponse) String() string {
	b, _ := jsoniter.Marshal(s)
	return string(b)
}

type Response struct {
	Message string `json:"message,omitempty"`
	Total   int32  `json:"total,omitempty"`
	Data    *Any   `json:"data,omitempty"`
}

func (s Response) String() string {
	b, _ := jsoniter.Marshal(s)
	return string(b)
}

type UserContext struct {
	UserID        string `json:"user_id,omitempty"`
	Platform      string `json:"platform,omitempty"`
	ClientVersion string `json:"client_version,omitempty"`
	Token         string `json:"token,omitempty"`
	ClientIP      string `json:"client_ip,omitempty"`
	RequestID     string `json:"request_id,omitempty"`
}

func (s UserContext) String() string {
	b, _ := jsoniter.Marshal(s)
	return string(b)
}

type service struct{}

// RpcContextFromHeader 从 httprouter.Context转换为grpc中所需的用户上下文
func RpcContextFromHeader(header string) *UserContext {
	var ctx *UserContext
	_ = jsoniter.UnmarshalFromString(header, ctx)
	return ctx
}

// NewService 新建usercenter的grpc服务
func NewService() Repository {
	return service{}
}

func (s service) GetUser(ctx context.Context, req GetUserRequest) grpcbase.Response {
	log.Infof("GetUser begin 1111")
	if GetUserHandler != nil {
		log.Infof("GetUser begin 222")
		if req.Context == nil {
			log.Infof("GetUser begin 3333")
			panic("grpc context is nil and requestID must be set")
		}
		log.Infof("GetUser begin 4444")
		return grpcbase.RPCServerSideLogic("/pb.usercenter/GetUser", req.Context.RequestID, req, func(ctx context.Context, req interface{}) grpcbase.Response {
			return GetUserHandler(ctx, req.(GetUserRequest))
		})
	}
	return grpcbase.NotImplErrorResponse
}
