// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: okr.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinedTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string       `protobuf:"bytes,1,opt,name=Keyword,proto3" json:"Keyword,omitempty"`
	Paging  *Paging      `protobuf:"bytes,2,opt,name=Paging,proto3" json:"Paging,omitempty"`
	Context *UserContext `protobuf:"bytes,3,opt,name=Context,proto3" json:"Context,omitempty"`
	Type    []string     `protobuf:"bytes,4,rep,name=Type,proto3" json:"Type,omitempty"` //widget_meeting,widget_todo,widget_timecoll,widget_notice,meeting,task,time_collect
}

func (x *JoinedTasksRequest) Reset() {
	*x = JoinedTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datasyncer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinedTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinedTasksRequest) ProtoMessage() {}

func (x *JoinedTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasyncer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinedTasksRequest.ProtoReflect.Descriptor instead.
func (*JoinedTasksRequest) Descriptor() ([]byte, []int) {
	return file_datasyncer_proto_rawDescGZIP(), []int{0}
}

func (x *JoinedTasksRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *JoinedTasksRequest) GetPaging() *Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *JoinedTasksRequest) GetContext() *UserContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *JoinedTasksRequest) GetType() []string {
	if x != nil {
		return x.Type
	}
	return nil
}

type JoinedTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefID []string `protobuf:"bytes,1,rep,name=RefID,proto3" json:"RefID,omitempty"`
}

func (x *JoinedTasksResponse) Reset() {
	*x = JoinedTasksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datasyncer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinedTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinedTasksResponse) ProtoMessage() {}

func (x *JoinedTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasyncer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinedTasksResponse.ProtoReflect.Descriptor instead.
func (*JoinedTasksResponse) Descriptor() ([]byte, []int) {
	return file_datasyncer_proto_rawDescGZIP(), []int{1}
}

func (x *JoinedTasksResponse) GetRefID() []string {
	if x != nil {
		return x.RefID
	}
	return nil
}

var File_datasyncer_proto protoreflect.FileDescriptor

var file_datasyncer_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x61, 0x74, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x12, 0x4a, 0x6f, 0x69, 0x6e,
	0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x12, 0x29, 0x0a, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2b, 0x0a, 0x13, 0x4a,
	0x6f, 0x69, 0x6e, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x66, 0x49, 0x44, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x52, 0x65, 0x66, 0x49, 0x44, 0x32, 0x41, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x79, 0x6e, 0x63, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64,
	0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x65,
	0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_datasyncer_proto_rawDescOnce sync.Once
	file_datasyncer_proto_rawDescData = file_datasyncer_proto_rawDesc
)

func file_datasyncer_proto_rawDescGZIP() []byte {
	file_datasyncer_proto_rawDescOnce.Do(func() {
		file_datasyncer_proto_rawDescData = protoimpl.X.CompressGZIP(file_datasyncer_proto_rawDescData)
	})
	return file_datasyncer_proto_rawDescData
}

var file_datasyncer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_datasyncer_proto_goTypes = []interface{}{
	(*JoinedTasksRequest)(nil),  // 0: pb.JoinedTasksRequest
	(*JoinedTasksResponse)(nil), // 1: pb.JoinedTasksResponse
	(*Paging)(nil),              // 2: pb.Paging
	(*UserContext)(nil),         // 3: pb.UserContext
	(*Response)(nil),            // 4: pb.Response
}
var file_datasyncer_proto_depIdxs = []int32{
	2, // 0: pb.JoinedTasksRequest.Paging:type_name -> pb.Paging
	3, // 1: pb.JoinedTasksRequest.Context:type_name -> pb.UserContext
	0, // 2: pb.DataSyncer.JoinedTasks:input_type -> pb.JoinedTasksRequest
	4, // 3: pb.DataSyncer.JoinedTasks:output_type -> pb.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_datasyncer_proto_init() }
func file_datasyncer_proto_init() {
	if File_datasyncer_proto != nil {
		return
	}
	file_grpc_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_datasyncer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinedTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datasyncer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinedTasksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datasyncer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datasyncer_proto_goTypes,
		DependencyIndexes: file_datasyncer_proto_depIdxs,
		MessageInfos:      file_datasyncer_proto_msgTypes,
	}.Build()
	File_datasyncer_proto = out.File
	file_datasyncer_proto_rawDesc = nil
	file_datasyncer_proto_goTypes = nil
	file_datasyncer_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataSyncerClient is the client API for DataSyncer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataSyncerClient interface {
	JoinedTasks(ctx context.Context, in *JoinedTasksRequest, opts ...grpc.CallOption) (*Response, error)
}

type dataSyncerClient struct {
	cc grpc.ClientConnInterface
}

func NewDataSyncerClient(cc grpc.ClientConnInterface) DataSyncerClient {
	return &dataSyncerClient{cc}
}

func (c *dataSyncerClient) JoinedTasks(ctx context.Context, in *JoinedTasksRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.DataSyncer/JoinedTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataSyncerServer is the server API for DataSyncer service.
type DataSyncerServer interface {
	JoinedTasks(context.Context, *JoinedTasksRequest) (*Response, error)
}

// UnimplementedDataSyncerServer can be embedded to have forward compatible implementations.
type UnimplementedDataSyncerServer struct {
}

func (*UnimplementedDataSyncerServer) JoinedTasks(context.Context, *JoinedTasksRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinedTasks not implemented")
}

func RegisterDataSyncerServer(s *grpc.Server, srv DataSyncerServer) {
	s.RegisterService(&_DataSyncer_serviceDesc, srv)
}

func _DataSyncer_JoinedTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinedTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncerServer).JoinedTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DataSyncer/JoinedTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncerServer).JoinedTasks(ctx, req.(*JoinedTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataSyncer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DataSyncer",
	HandlerType: (*DataSyncerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinedTasks",
			Handler:    _DataSyncer_JoinedTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "okr.proto",
}
