// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by grpc_generate_tools(grpcgengo) at
//

package okr

import (
	"context"
	"log"

	"github.com/go-kit/kit/endpoint"
	"github.com/pengcainiao2/zero/rpcx/grpcbase"
	"google.golang.org/grpc"
)

func init() {
	grpcbase.RegisterClients(grpcbase.ServerAddr(grpcbase.OkrSVC), &clientBinding{})
}

type clientBinding struct {
	getOkr endpoint.Endpoint
}

func (c *clientBinding) GetOkr(ctx context.Context, params GetOkrRequest) grpcbase.Response {
	if ctx == nil {
		ctx = context.Background()
		log.Println("GRPC：GetOkr request context is nil，trace span将无法生效")
	}
	response, err := c.getOkr(ctx, params)
	if err != nil {
		return grpcbase.Response{
			Message: err.Error(),
		}
	}
	r := response.(grpcbase.Response)
	return r
}

func (c *clientBinding) GRPCClient(cc *grpc.ClientConn) interface{} {
	c.newClient(cc)
	return c
}

func (c *clientBinding) newClient(cc *grpc.ClientConn) {

	c.getOkr = grpcbase.CreateGRPCClientEndpoint(cc, "pb.Okr",
		"GetOkr",
		encodeGetOkrRequest,
		decodeGetOkrResponse)
}
